---
title: "Temporal RVL"
---

```{r}
library(tidyverse)
library(ggpubr)

convert_filename_to_depth_stream <- function(filename) {
  if(filename == "ppt2-empty") {
    return("DS1")
  } else if(filename == "ppt2-sitting") {
    return("DS2")
  } else if(filename == "comm-empty") {
    return("DS3")
  } else if(filename == "comm-standing") {
    return("DS4")
  } else if(filename == "comm-camera-movement") {
    return("DS5")
  } else {
    stop()
  }
}

convert_type_and_thresholds_to_type <- function(type, change_threshold, invalidation_threshold) {
  if(type == "rvl") {
    return("RVL")
  }
  if(type != "trvl") {
    stop()
  }
  
  if(change_threshold == 0) {
    # TRVL without preprocessing
    return("TRVL w/o Preprocessing")
  } else if(invalidation_threshold == 0) {
    # TRVL without invalidation tolerance
    return("TRVL w/o Invalitiy Tolerance")
  } else if(change_threshold == 5) {
    return("TRVL 0.5 cm")
  } else if(change_threshold == 10) {
    return("TRVL 1 cm")
  } else if(change_threshold == 20) {
    return("TRVL 2 cm")
  } else if(change_threshold == 30) {
    return("TRVL 3 cm")
  }
}

result_data <- read_csv("../output/paper-result.csv") %>%
  mutate(depth_stream = map_chr(filename, convert_filename_to_depth_stream),
         type = pmap_chr(list(type, change_threshold, invalidation_threshold), convert_type_and_thresholds_to_type)) %>%
  mutate(depth_stream = factor(depth_stream)) %>%
  select(depth_stream, type, compression_ratio, average_compression_time, average_decompression_time, average_psnr)
```

```{r paper-methods, fig.width=6, fig.height=5}
to_methods_type <- function(type) {
  if(type == "RVL" | type == "TRVL w/o Preprocessing" | type == "TRVL w/o Invalitiy Tolerance")
    return(type)
  
  if(type == "TRVL 1 cm")
    return("TRVL")
  
  return(NA)
}

methods_data <- result_data %>%
  mutate(type = map(type, to_methods_type)) %>%
  filter(!is.na(type)) %>%
  mutate(type = factor(type, c("RVL", "TRVL w/o Preprocessing", "TRVL w/o Invalitiy Tolerance", "TRVL")))

methods_data %>%
  mutate(label = map_chr(compression_ratio, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = compression_ratio, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Compression Ratio", fill = "Method") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.4) +
  theme(legend.position = "bottom")

methods_data %>%
  mutate(label = map_chr(average_compression_time, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = average_compression_time, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Compression Time (ms)", fill = "Method") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.4) +
  theme(legend.position = "bottom")

methods_data %>%
  mutate(label = map_chr(average_decompression_time, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = average_decompression_time, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Decompression Time (ms)", fill = "Method") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.4) +
  theme(legend.position = "bottom")

methods_data %>%
  mutate(label = map_chr(average_psnr, ~ formatC(.x,, digits = 2, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = average_psnr, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Average Decompression Time (ms)", fill = "Method") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.4) +
  theme(legend.position = "bottom")
```

```{r paper-thresholds, fig.width=6, fig.height=5}
to_thresholds_type <- function(type) {
  if(type == "TRVL 0.5 cm")
    return("0.5 cm")
  
  if(type == "TRVL 1 cm")
    return("1 cm")
  
  if(type == "TRVL 2 cm")
    return("2 cm")
  
  if(type == "TRVL 3 cm")
    return("3 cm")
  
  return(NA)
}

thresholds_data <- result_data %>%
  mutate(type = map(type, to_thresholds_type)) %>%
  filter(!is.na(type)) %>%
  mutate(type = factor(type, c("0.5 cm", "1 cm", "2 cm", "3 cm")))

thresholds_data %>%
  mutate(label = map_chr(compression_ratio, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = compression_ratio, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Compression Ratio", fill = "Threshold") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.4) +
  theme(legend.position = "bottom")

thresholds_data %>%
  mutate(label = map_chr(average_compression_time, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = average_compression_time, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Compression Time (ms)", fill = "Threshold") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.4) +
  theme(legend.position = "bottom")

thresholds_data %>%
  mutate(label = map_chr(average_decompression_time, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = average_decompression_time, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Decompression Time (ms)", fill = "Threshold") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.4) +
  theme(legend.position = "bottom")

thresholds_data %>%
  mutate(label = map_chr(average_psnr, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = average_psnr, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "PSNR", fill = "Threshold") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.4) +
  theme(legend.position = "bottom")
```

```{r poster, fig.width=12, fig.height=3.5}
to_poster_type <- function(type) {
  if(type == "RVL")
    return(type)
  
  if(type == "TRVL 0.5 cm")
    return("TRVL 0.5 cm")
  
  if(type == "TRVL 1 cm")
    return("TRVL 1 cm")
  
  if(type == "TRVL 2 cm")
    return("TRVL 2 cm")
  
  return(NA)
}

poster_data <- result_data %>%
  mutate(type = map(type, to_poster_type)) %>%
  filter(!is.na(type)) %>%
  mutate(type = factor(type, c("RVL", "TRVL 0.5 cm", "TRVL 1 cm", "TRVL 2 cm")))

p1 <- poster_data %>%
  mutate(label = map_chr(compression_ratio, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = compression_ratio, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Compression Ratio", fill = "Type") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.1) +
  theme(legend.position = "bottom")

p2 <- poster_data %>%
  mutate(label = map_chr(average_compression_time, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = average_compression_time, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Compression Time (ms)", fill = "Type") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.1) +
  theme(legend.position = "bottom")

p3 <- poster_data %>%
  mutate(label = map_chr(average_decompression_time, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = average_decompression_time, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "Decompression Time (ms)", fill = "Type") +
  geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.1) +
  theme(legend.position = "bottom")

p4 <- poster_data %>%
  mutate(label = map_chr(average_psnr, ~ formatC(.x,, digits = 1, format = "f"))) %>%
  ggplot(aes(x = depth_stream, y = average_psnr, fill = type)) +
  geom_col(position = "dodge") +
  labs(x = "Depth Stream", y = "PSNR", fill = "Type") +
  #geom_text(aes(label = label), position = position_dodge(0.9), vjust = -0.4) +
  geom_text(aes(label = ifelse(label == "0.0", "", label)), position = position_dodge(0.9), vjust = -0.1) +
  theme(legend.position = "bottom")

ggarrange(p1, p2, p3, p4, ncol = 4, nrow = 1,
          common.legend = TRUE, legend = "bottom")
```

```{r}
get_ratio <- function(variable) {
  return(variable[[3]] / variable[[1]])
}

comparison_table <- result_data %>%
  filter(depth_stream != "DS1" & depth_stream != "DS5") %>%
  group_by(type) %>%
  summarise(compression_ratio = mean(compression_ratio),
            average_compression_time = mean(average_compression_time),
            average_decompression_time = mean(average_decompression_time))

comparison_table

str_c("compression ratio: ", get_ratio(comparison_table$compression_ratio))
str_c("average compression time: ", get_ratio(comparison_table$average_compression_time))
str_c("average decompression time: ", get_ratio(comparison_table$average_decompression_time))

result_data %>%
  filter(type == "TRVL w/o Invalitiy Tolerance") %>%
  pull(average_psnr) %>%
  { str_c("TRVL w/o Invalitiy Tolerance PSNR mean: ", mean(.), ", min: ", min(.)) }

result_data %>%
  filter(type == "TRVL 1 cm") %>%
  pull(average_psnr) %>%
  { str_c("TRVL PSNR mean: ", mean(.), ", min: ", min(.)) }
```
